from typing import Union, Any, Dict, List, Optional
from .models import ArtifactCodeV3, ArtifactMarkdownV3, ArtifactV3 # Assuming models.py is in the same directory

def is_artifact_code_content(content: Any) -> bool:
    return (
        isinstance(content, dict) and
        content.get("type") == "code"
    ) or (
        hasattr(content, "type") and
        getattr(content, "type") == "code"
    )

def is_artifact_markdown_content(content: Any) -> bool:
    return (
        isinstance(content, dict) and
        content.get("type") == "text"
    ) or (
        hasattr(content, "type") and
        getattr(content, "type") == "text"
    )

def get_artifact_content(artifact: ArtifactV3) -> Union[ArtifactCodeV3, ArtifactMarkdownV3]:
    if not artifact:
        raise ValueError("No artifact found.")

    current_content = next((c for c in artifact.contents if c.index == artifact.currentIndex), None)

    if not current_content:
        if not artifact.contents:
            raise ValueError("Artifact has no contents.")
        return artifact.contents[-1]
    return current_content

# Placeholder for other utility functions to be added later

# --- Appended content starts (from previous subtask) ---

import base64
import os
import json
import uuid
from PyPDF2 import PdfReader
from io import BytesIO
from langchain_core.messages import AIMessage, BaseMessage, SystemMessage, HumanMessage # Or specific message types
# from langchain.chat_models.universal import init_chat_model # This will be handled by the new block's try-except
# (LangChain's init_chat_model might be elsewhere or require specific imports based on version)
# from langchain_community.chat_models.universal import init_chat_model # Possible location

from .models import (
    Reflections,
    # ArtifactMarkdownV3, # Already imported
    # ArtifactCodeV3, # Already imported
    CustomModelConfig,
    ContextDocument,
    SearchResult,
    ExaMetadata,
    ProgrammingLanguageOptions, # For createAIMessageFromWebResults example if needed
    OpenCanvasGraphState # For type hinting config/state if we adapt
)

# Environment variables that were in process.env in JS
# These would be loaded by python-dotenv from a .env file
# For now, accessing via os.getenv

# Constants from @opencanvas/shared/constants
OC_WEB_SEARCH_RESULTS_MESSAGE_KEY = "oc_web_search_results_message_key"
CONTEXT_DOCUMENTS_NAMESPACE = "context_documents_namespace" # For getContextDocuments if fully ported

# Model lists from @opencanvas/shared/models (ensure these are kept up-to-date)
TEMPERATURE_EXCLUDED_MODELS = ["o1-mini", "o3-mini", "o1", "o4-mini"]
LANGCHAIN_USER_ONLY_MODELS = [
    "o1", "gpt-4o", "gpt-4.5-preview",
    "claude-3-5-sonnet-latest", "claude-3-7-sonnet-latest",
    "gemini-2.0-flash-thinking-exp-01-21", "gemini-2.5-pro-preview-05-06",
    "claude-sonnet-4-0", "claude-opus-4-0", "gpt-4.1"
]
THINKING_MODELS = [
  "accounts/fireworks/models/deepseek-r1",
  "groq/deepseek-r1-distill-llama-70b",
]
NON_STREAMING_TOOL_CALLING_MODELS = [
  "gemini-1.5-flash",
  "gemini-2.5-pro-preview-05-06",
  "gemini-2.5-flash-preview-05-20",
]
NON_STREAMING_TEXT_MODELS = [
  "o1",
  "gemini-2.0-flash-thinking-exp-01-21",
]

def clean_base64(base64_string: str) -> str:
    return base64_string.split(',')[-1] # Simplistic, similar to replace(/^data:.*?;base64,/, "")

def format_reflections(
    reflections: Reflections,
    only_style: bool = False,
    only_content: bool = False
) -> str:
    if only_style and only_content:
        raise ValueError("Cannot specify both only_style and only_content as True.")

    style_rules_str = "No style guidelines found."
    if reflections.styleRules:
        # TS code had JSON.parse logic for strings, assuming Pydantic model gets list directly
        style_rules_str = "\n- ".join(reflections.styleRules)

    content_rules_str = "No memories/facts found."
    if reflections.content:
        content_rules_str = "\n- ".join(reflections.content)

    style_string = f"""The following is a list of style guidelines previously generated by you:
<style-guidelines>
- {style_rules_str}
</style-guidelines>"""
    content_string = f"""The following is a list of memories/facts you previously generated about the user:
<user-facts>
- {content_rules_str}
</user-facts>"""

    if only_style:
        return style_string
    if only_content:
        return content_string

    return f"{style_string}\n\n{content_string}"

# getFormattedReflections depends on a 'store' which is part of LangGraph's config.
# For now, we might need to adapt it or assume reflections are passed directly.
# Placeholder:
# async def get_formatted_reflections(config: Dict[str, Any]) -> str:
#     # This function needs to be adapted based on how state/config is managed in FastAPI
#     # For now, let's assume reflections object is directly available or passed in state
#     assistant_id = config.get("configurable", {}).get("assistant_id")
#     if not assistant_id:
#         return "No assistant_id found in config."
#     # Actual store interaction would go here
#     # reflections_data = await store.get(["memories", assistant_id], "reflection")
#     # For now, returning a default if not found.
#     # This part needs actual implementation once store mechanism is decided.
#     return "No reflections found (get_formatted_reflections needs store integration)."


def format_artifact_content(
    content: Union[ArtifactMarkdownV3, ArtifactCodeV3],
    shorten_content: bool = False
) -> str:
    artifact_text: str
    if isinstance(content, ArtifactCodeV3): # Or use is_artifact_code_content
        artifact_text = content.code[:500] if shorten_content else content.code
    elif isinstance(content, ArtifactMarkdownV3): # Or use is_artifact_markdown_content
        artifact_text = content.fullMarkdown[:500] if shorten_content else content.fullMarkdown
    else:
        raise TypeError("Invalid content type for formatting.")

    return f"Title: {content.title}\nArtifact type: {content.type}\nContent: {artifact_text}"

def format_artifact_content_with_template(
    template: str,
    content: Union[ArtifactMarkdownV3, ArtifactCodeV3],
    shorten_content: bool = False
) -> str:
    formatted_artifact = format_artifact_content(content, shorten_content)
    return template.replace("{artifact}", formatted_artifact)

def get_string_from_content(message_content: Union[str, List[Dict[str, Any]]]) -> str:
    if isinstance(message_content, str):
        return message_content

    # Assuming content is a list of parts, e.g. from AIMessage.content
    # [{'type': 'text', 'text': 'Hello'}]
    text_parts = []
    for part in message_content:
        if isinstance(part, dict) and part.get("type") == "text" and "text" in part:
            text_parts.append(part["text"])
    return "\n".join(text_parts)


def convert_pdf_to_text(base64_pdf: str) -> str:
    try:
        cleaned_base64 = clean_base64(base64_pdf)
        pdf_buffer = BytesIO(base64.b64decode(cleaned_base64))
        reader = PdfReader(pdf_buffer)
        text_parts = [page.extract_text() for page in reader.pages if page.extract_text()]
        return "\n".join(text_parts)
    except Exception as e:
        print(f"Error converting PDF to text: {e}")
        raise

# This is a complex function. `config` here would be the equivalent of LangGraphRunnableConfig
# We'll assume it's a dictionary for now, containing 'configurable' and other necessary keys.
def get_model_config(config: Dict[str, Any], is_tool_calling: bool = False) -> Dict[str, Any]:
    configurable_dict = config.get("configurable", {})
    custom_model_name = configurable_dict.get("customModelName")
    if not custom_model_name:
        raise ValueError("Model name is missing in config.")

    model_config_obj: Optional[CustomModelConfig] = configurable_dict.get("modelConfig") # Assuming it's passed as a Pydantic model or dict

    # Azure
    if custom_model_name.startswith("azure/"):
        actual_model_name = custom_model_name.replace("azure/", "")
        if is_tool_calling and "o1" in actual_model_name: # o1 models don't support tools
            actual_model_name = "gpt-4o" # Fallback
        return {
            "modelName": actual_model_name,
            "modelProvider": "azure_openai",
            "azureConfig": {
                "azureOpenAIApiKey": os.getenv("_AZURE_OPENAI_API_KEY", ""),
                "azureOpenAIApiInstanceName": os.getenv("_AZURE_OPENAI_API_INSTANCE_NAME", ""),
                "azureOpenAIApiDeploymentName": os.getenv("_AZURE_OPENAI_API_DEPLOYMENT_NAME", ""),
                "azureOpenAIApiVersion": os.getenv("_AZURE_OPENAI_API_VERSION", "2024-08-01-preview"),
                "azureOpenAIBasePath": os.getenv("_AZURE_OPENAI_API_BASE_PATH"),
            },
            "modelConfig": model_config_obj # Pass along the original modelConfig if present
        }

    provider_config = {
        "modelName": custom_model_name,
        "modelConfig": model_config_obj
    }

    # OpenAI
    if "gpt-" in custom_model_name or "o1" in custom_model_name or "o3" in custom_model_name:
        actual_model_name = provider_config["modelName"]
        if is_tool_calling and "o1" in actual_model_name:
            actual_model_name = "gpt-4o"
        return {
            **provider_config,
            "modelName": actual_model_name,
            "modelProvider": "openai",
            "apiKey": os.getenv("OPENAI_API_KEY"),
        }
    # Anthropic
    if "claude-" in custom_model_name:
        return {
            **provider_config,
            "modelProvider": "anthropic",
            "apiKey": os.getenv("ANTHROPIC_API_KEY"),
        }
    # Fireworks
    if "fireworks/" in custom_model_name:
        actual_model_name = provider_config["modelName"]
        # Fallback for tool calling if not the specific capable model
        if is_tool_calling and actual_model_name != "accounts/fireworks/models/llama-v3p3-70b-instruct":
            actual_model_name = "accounts/fireworks/models/llama-v3p3-70b-instruct"
        return {
            **provider_config,
            "modelName": actual_model_name,
            "modelProvider": "fireworks",
            "apiKey": os.getenv("FIREWORKS_API_KEY"),
        }
    # Groq
    if custom_model_name.startswith("groq/"):
        actual_model_name = custom_model_name.replace("groq/", "")
        return {
            "modelName": actual_model_name,
            "modelProvider": "groq",
            "apiKey": os.getenv("GROQ_API_KEY"),
            "modelConfig": model_config_obj # Groq might not use modelConfig but pass for consistency
        }
    # Google GenAI
    if "gemini-" in custom_model_name:
        actual_model_name = provider_config["modelName"]
        if is_tool_calling and "thinking" in actual_model_name: # Gemini thinking does not support tools
            actual_model_name = "gemini-2.0-flash-exp" # Example fallback
        return {
            **provider_config,
            "modelName": actual_model_name,
            "modelProvider": "google-genai", # or "google_vertexai" or "gemini" depending on LangChain version
            "apiKey": os.getenv("GOOGLE_API_KEY"),
        }
    # Ollama
    if custom_model_name.startswith("ollama-"):
        return {
            "modelName": custom_model_name.replace("ollama-", ""),
            "modelProvider": "ollama",
            "baseUrl": os.getenv("OLLAMA_API_URL", "http://localhost:11434"), # host.docker.internal might not work from python server
            "modelConfig": model_config_obj
        }

    raise ValueError(f"Unknown model provider for: {custom_model_name}")


def optionally_get_system_prompt_from_config(config: Dict[str, Any]) -> Optional[str]:
    return config.get("configurable", {}).get("systemPrompt")

def is_using_o1_mini_model(config: Dict[str, Any]) -> bool:
    model_params = get_model_config(config) # is_tool_calling defaults to False
    return "o1-mini" in model_params.get("modelName", "")

def create_ai_message_from_web_results(web_results: List[SearchResult]) -> AIMessage:
    web_results_str_parts = []
    for i, r in enumerate(web_results):
        # Ensure metadata is present, use defaults if not. Pydantic models should handle this with Optional.
        published_date = r.metadata.publishedDate if r.metadata else "Unknown"
        author = r.metadata.author if r.metadata else "Unknown"
        title = r.metadata.title if r.metadata else "Unknown title"
        url = r.metadata.url if r.metadata else "Unknown URL"

        part = (
            f'<search-result index="{i}" publishedDate="{published_date}" author="{author}">\n'
            f'  [{title}]({url})\n'
            f'  {r.page_content}\n'
            f'</search-result>'
        )
        web_results_str_parts.append(part)

    web_results_str = "\n\n".join(web_results_str_parts)
    content = f"Here is some additional context I found from searching the web. This may be useful:\n\n{web_results_str}"

    return AIMessage(
        content=content,
        # id=f"web-search-results-{uuid.uuid4()}", # In LangChain AIMessage id is not a standard param in constructor
        additional_kwargs={
            OC_WEB_SEARCH_RESULTS_MESSAGE_KEY: True,
            "webSearchResults": [res.dict(exclude_none=True) for res in web_results], # Store Pydantic as dict
            "webSearchStatus": "done",
        }
    )

# Functions still needing careful porting or adaptation for Python context:
# - getFormattedReflections (store access)
# - getUserFromConfig (Supabase client, async in JS)
# - getModelFromConfig (uses getUserFromConfig, initChatModel, complex params)
# - createContextDocumentMessagesAnthropic, Gemini, OpenAI (async in JS, PDF conversion)
# - getContextDocuments (store access)
# - createContextDocumentMessages (orchestrates above, async in JS)
# - formatMessages (BaseMessage structure in Python)

# Adding a basic Supabase user fetch for getModelFromConfig, needs supabase client init
# This is a simplified synchronous version for now.
# from supabase import create_client, Client # This will be handled by the new block's try-except
# def get_user_from_config_sync(config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
#     supabase_url = os.getenv("NEXT_PUBLIC_SUPABASE_URL")
#     supabase_key = os.getenv("SUPABASE_SERVICE_ROLE") # Using service role key for server-side user fetch

#     if not supabase_url or not supabase_key:
#         print("Supabase URL or service key not configured.")
#         return None

#     supabase_session = config.get("configurable", {}).get("supabase_session")
#     access_token = supabase_session.get("access_token") if isinstance(supabase_session, dict) else None

#     if not access_token:
#         # print("No access token in config.")
#         return None # Often this is okay, not all models need user context

#     try:
#         supabase: Client = create_client(supabase_url, supabase_key)
#         user_response = supabase.auth.get_user(access_token)
#         if user_response.user:
#             return user_response.user.dict() # Pydantic model to dict
#         return None
#     except Exception as e:
#         print(f"Error fetching user from Supabase: {e}")
#         return None

# async def get_model_from_config(...) will be more involved.

# --- Appended content starts (current subtask) ---

# Imports for newly added functions
from langchain_core.runnables import RunnableConfig # For type hinting if we simulate LangGraphRunnableConfig
from langchain_core.chat_history import BaseChatMessageHistory # If we need to handle history objects
from langchain.memory import ConversationBufferMemory # Example, if reflections/context come from memory obj

# Attempt to import init_chat_model from common locations
try:
    from langchain.chat_models.universal import init_chat_model
except ImportError:
    try:
        from langchain_community.chat_models.universal import init_chat_model
    except ImportError:
        # This will cause a runtime error if get_model_from_config is called
        # and init_chat_model was not found.
        print("WARNING: init_chat_model not found in langchain.chat_models.universal or langchain_community.chat_models.universal")
        init_chat_model = None

try:
    from supabase import create_client, Client
    got_supabase = True
except ImportError:
    got_supabase = False
    print("WARNING: supabase library not installed, getUserFromConfig related functions will not work.")


# --- Supabase User Fetching ---
# Synchronous version, as FastAPI calls are typically sync unless using async def
def get_user_from_config(config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    if not got_supabase:
        # print("Supabase library not available.")
        return None # Silently return None if Supabase is not installed for wider usability

    supabase_url = os.getenv("NEXT_PUBLIC_SUPABASE_URL")
    # For server-side, service_role_key is often used.
    # The JS version might have been using anon_key if it was client-side logic passed to backend.
    # Let's check for both, prioritizing service role.
    supabase_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("NEXT_PUBLIC_SUPABASE_ANON_KEY")

    if not supabase_url or not supabase_key:
        # print("Supabase URL or Key not configured.")
        return None

    configurable = config.get("configurable", {})
    supabase_session = configurable.get("supabase_session")
    access_token = None
    if isinstance(supabase_session, dict):
        access_token = supabase_session.get("access_token")
    elif hasattr(supabase_session, 'access_token'): # If it's an object
        access_token = supabase_session.access_token


    if not access_token:
        # print("No access token in config's supabase_session.")
        return None # This is often a valid state; not all operations require a user.

    try:
        supabase_client: Client = create_client(supabase_url, supabase_key)
        # In supabase-py v1.x, it's auth.get_user(jwt=access_token)
        # In supabase-py v2.x, it might be slightly different or use user_management
        user_response = supabase_client.auth.get_user(access_token) # For supabase-py v1.x

        if user_response and hasattr(user_response, 'user') and user_response.user:
            # Assuming user_response.user is a Pydantic model or similar
            if hasattr(user_response.user, 'dict'):
                 return user_response.user.dict()
            elif isinstance(user_response.user, dict): # if it's already a dict
                 return user_response.user
            else: # Try to convert to dict if it's some other object
                try:
                    return dict(user_response.user)
                except TypeError:
                    print(f"Could not convert supabase user object to dict: {type(user_response.user)}")
                    return None
        # print("No user found for the given access token.")
        return None
    except Exception as e:
        print(f"Error fetching user from Supabase: {e}")
        return None

# --- Model Initialization ---
def get_model_from_config(
    config: Dict[str, Any],
    temperature: Optional[float] = None,
    max_tokens: Optional[int] = None,
    is_tool_calling: bool = False
) -> Optional[Any]: # Return type should be BaseChatModel from LangChain
    if init_chat_model is None:
        raise ImportError("init_chat_model could not be imported. Please check LangChain installation.")

    model_params = get_model_config(config, is_tool_calling=is_tool_calling)

    # modelConfig from the original config might contain temp/max_tokens defaults
    # These can be overridden by direct parameters to this function
    cfg_model_config: Optional[CustomModelConfig] = model_params.get("modelConfig")

    current_temp = temperature
    if current_temp is None and cfg_model_config and cfg_model_config.temperatureRange:
        current_temp = cfg_model_config.temperatureRange.get("current", 0.5)
    elif current_temp is None:
        current_temp = 0.5 # Default fallback

    current_max_tokens = max_tokens
    if current_max_tokens is None and cfg_model_config and cfg_model_config.maxTokens:
        current_max_tokens = cfg_model_config.maxTokens.get("current", 4096)
    elif current_max_tokens is None:
        current_max_tokens = 4096 # Default fallback

    # LangChain user-only model check
    if model_params["modelName"] in LANGCHAIN_USER_ONLY_MODELS:
        user = get_user_from_config(config) # Sync call
        if not user:
            raise PermissionError("Unauthorized. Cannot use LangChain user-only models without a user.")
        if not user.get("email", "").endswith("@langchain.dev"):
            raise PermissionError("Unauthorized. User email must be @langchain.dev for these models.")

    # Parameters for init_chat_model
    init_params = {
        "model_name": model_params["modelName"],
        "model_provider": model_params["modelProvider"],
    }

    if model_params["modelName"] not in TEMPERATURE_EXCLUDED_MODELS:
        init_params["temperature"] = current_temp
        init_params["max_tokens"] = current_max_tokens
    else:
        # For models that don't take temperature, they might take max_completion_tokens
        init_params["max_completion_tokens"] = current_max_tokens
        # init_params["streaming"] = False # as per original TS

    if model_params.get("baseUrl"):
        init_params["base_url"] = model_params["baseUrl"]
    if model_params.get("apiKey"):
        init_params["api_key"] = model_params["apiKey"]

    if model_params.get("azureConfig"):
        azure_cfg = model_params["azureConfig"]
        init_params.update({
            "azure_openai_api_key": azure_cfg.get("azureOpenAIApiKey"),
            "azure_openai_api_instance_name": azure_cfg.get("azureOpenAIApiInstanceName"),
            "azure_openai_api_deployment_name": azure_cfg.get("azureOpenAIApiDeploymentName"),
            "azure_openai_api_version": azure_cfg.get("azureOpenAIApiVersion"),
            "azure_openai_api_base_path": azure_cfg.get("azureOpenAIBasePath"),
        })

    # Remove None values from init_params as init_chat_model might not like them
    init_params = {k: v for k, v in init_params.items() if v is not None}

    try:
        # print(f"Initializing model with params: {init_params}")
        return init_chat_model(**init_params)
    except Exception as e:
        print(f"Error initializing chat model {model_params['modelName']}: {e}")
        raise

# --- Context Document Processing ---
# For these, we assume `documents` are passed directly, adapting from store-based retrieval

def _create_context_document_messages_anthropic_native(doc_data: str, doc_type: str) -> Dict[str, Any]:
    return {
        "type": "document", # This structure might need verification with Python LangChain Anthropic
        "source": {
            "type": "base64",
            "media_type": doc_type,
            "data": clean_base64(doc_data),
        }
    }

# Changed from async def to def as Python PDF processing is sync
def _create_context_document_messages_anthropic(documents: List[ContextDocument], native_pdf_support: bool) -> List[Dict[str, Any]]:
    messages = []
    for doc in documents:
        if doc.type == "application/pdf" and native_pdf_support:
            messages.append(_create_context_document_messages_anthropic_native(doc.data, doc.type))
        else:
            text = ""
            if doc.type == "application/pdf" and not native_pdf_support:
                text = convert_pdf_to_text(doc.data)
            elif doc.type.startswith("text/") or doc.type == "text":
                text = base64.b64decode(clean_base64(doc.data)).decode('utf-8') if doc.type.startswith("text/") else doc.data
            else:
                print(f"Unsupported document type for Anthropic context: {doc.type}")
                continue
            messages.append({"type": "text", "text": text})
    return messages

def _create_context_document_messages_gemini(documents: List[ContextDocument]) -> List[Dict[str, Any]]:
    gemini_parts = []
    for doc in documents:
        if doc.type == "application/pdf":
            # Corrected structure for Gemini inline_data
            gemini_parts.append({
                "inline_data": {
                    "mime_type": doc.type,
                    "data": clean_base64(doc.data)
                }
            })
        elif doc.type.startswith("text/") or doc.type == "text":
            text = base64.b64decode(clean_base64(doc.data)).decode('utf-8') if doc.type.startswith("text/") else doc.data
            gemini_parts.append({"text": text})
        else:
            print(f"Unsupported document type for Gemini context: {doc.type}")
            continue
    return gemini_parts

def _create_context_document_messages_openai(documents: List[ContextDocument]) -> List[Dict[str, Any]]:
    messages = []
    for doc in documents:
        text = ""
        if doc.type == "application/pdf":
            text = convert_pdf_to_text(doc.data)
        elif doc.type.startswith("text/") or doc.type == "text":
            text = base64.b64decode(clean_base64(doc.data)).decode('utf-8') if doc.type.startswith("text/") else doc.data
        else:
            print(f"Unsupported document type for OpenAI context: {doc.type}")
            continue
        messages.append({"type": "text", "text": text})
    return messages

def create_context_document_messages(
    config: Dict[str, Any],
    context_documents_list: List[ContextDocument]
) -> List[BaseMessage]:

    if not context_documents_list:
        return []

    model_cfg = get_model_config(config)
    model_provider = model_cfg["modelProvider"]
    model_name = model_cfg["modelName"]

    processed_doc_content: List[Union[str, Dict[str, Any]]] = [] # Allow strings or dicts

    if model_provider == "openai":
        # OpenAI expects list of text content or image URLs, etc.
        # _create_context_document_messages_openai returns List[Dict{"type":"text", "text":"..."}]
        # We need to extract the text string for HumanMessage content if it's simple text.
        # However, HumanMessage can take a list of such dicts directly.
        processed_doc_content.extend(_create_context_document_messages_openai(context_documents_list))
    elif model_provider == "anthropic":
        native_support = "3-5-sonnet" in model_name
        processed_doc_content.extend(_create_context_document_messages_anthropic(context_documents_list, native_pdf_support=native_support))
    elif model_provider == "google-genai":
        # Gemini messages usually are `parts: [...]`
        # _create_context_document_messages_gemini returns the list of parts.
        processed_doc_content.extend(_create_context_document_messages_gemini(context_documents_list))
    else:
        # Fallback for other providers: treat as text
        temp_processed = _create_context_document_messages_openai(context_documents_list)
        processed_doc_content.extend(temp_processed)


    if not processed_doc_content:
        return []

    final_content_parts: List[Union[str, Dict]] = [{
        "type": "text",
        "text": "Use the file(s) and/or text below as context when generating your response."
    }]
    final_content_parts.extend(processed_doc_content)

    return [HumanMessage(content=final_content_parts)]


# --- Message Formatting ---
def format_messages(messages: List[BaseMessage]) -> str:
    formatted_strs = []
    for idx, msg in enumerate(messages):
        msg_type = msg.type

        content_str = ""
        if isinstance(msg.content, str):
            content_str = msg.content
        elif isinstance(msg.content, list):
            texts = []
            for part in msg.content:
                if isinstance(part, dict) and part.get("type") == "text" and "text" in part :
                    texts.append(part["text"])
                # Could add handling for other complex types if needed, e.g. image URLs
            content_str = "\n".join(texts)

        formatted_strs.append(f"<{msg_type} index=\"{idx}\">\n{content_str}\n</{msg_type}>")
    return "\n".join(formatted_strs)

def get_context_documents_from_state(current_state: OpenCanvasGraphState) -> List[ContextDocument]:
    print("WARNING: get_context_documents_from_state is a placeholder. Context documents should be passed to the graph.")
    return []

def get_formatted_reflections_from_state(current_state: OpenCanvasGraphState) -> str:
    print("WARNING: get_formatted_reflections_from_state is a placeholder. Reflections should be passed to the graph.")
    return "No reflections found (placeholder)."

import re

def extract_urls(text: str) -> List[str]:
    # Regex for markdown links: [text](url)
    markdown_link_regex = r'\[(?:[^\]\[]+)\]\((https?:\/\/[^\s\)]+)\)'
    # Regex for plain URLs
    plain_url_regex = r'https?:\/\/[^\s<\]]+(?:[^<.,:;"'\]\s)]|(?=\s|$))'

    urls = set()

    # Find and store URLs from markdown links, then replace them to avoid double matching
    processed_text = text
    for match in re.finditer(markdown_link_regex, text):
        urls.add(match.group(1))
        # Replace with spaces to maintain positions if needed, though not strictly necessary for just extraction
        processed_text = processed_text.replace(match.group(0), " " * len(match.group(0)))

    # Find plain URLs in the processed text
    for match in re.finditer(plain_url_regex, processed_text):
        urls.add(match.group(0))

    return list(urls)

def is_thinking_model(model_name: str) -> bool:
    # Ensure THINKING_MODELS is defined, e.g. at the top of this utils.py
    # THINKING_MODELS = ["accounts/fireworks/models/deepseek-r1", "groq/deepseek-r1-distill-llama-70b"] # Example
    return model_name in THINKING_MODELS

def extract_thinking_and_response_tokens(text: str) -> Dict[str, str]:
    think_start_tag = "<think>"
    think_end_tag = "</think>"

    start_index = text.find(think_start_tag)

    if start_index == -1:
        return {"thinking": "", "response": text.strip()}

    after_start_tag = text[start_index + len(think_start_tag):]
    end_index = after_start_tag.find(think_end_tag)

    if end_index == -1: # No closing tag
        return {
            "thinking": after_start_tag.strip(),
            "response": text[:start_index].strip()
        }

    thinking_content = after_start_tag[:end_index].strip()
    response_content = (text[:start_index] + after_start_tag[end_index + len(think_end_tag):]).strip()

    return {"thinking": thinking_content, "response": response_content}
